export const enum Error {
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_EMAIL = 'INVALID_EMAIL',
  MISSING_EMAIL = 'MISSING_EMAIL',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  NO_BODY = 'NO_BODY',
  NO_EXISTING_USER = 'NO_EXISTING_USER',
}
