export const enum Error {
  NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_AUTHENTICATION = 'NO_AUTHENTICATION',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
}
